-- ============================================================
-- Résumés d'exécution en français pour les exercices du
-- référentiel, condensés à partir des instructions détaillées
-- du dataset yuhonas/free-exercise-db (domaine public).
-- Affichés à côté du GIF de démonstration pendant la séance.
-- À exécuter dans Supabase > SQL Editor, une seule fois.
-- ============================================================

alter table exercise_catalog add column if not exists instructions_fr text;

update exercise_catalog set instructions_fr = 'Allongé sur le banc, prise un peu plus large que les épaules. Descends la barre lentement jusqu''à effleurer la poitrine, puis pousse en gardant les coudes alignés. Ne rebondis jamais la barre sur le torse.' where canonical_name = 'Développé couché barre';
update exercise_catalog set instructions_fr = 'Haltères alignées à hauteur de poitrine, coudes à 90°. Pousse vers le haut jusqu''à ce que les haltères se touchent presque, puis redescends lentement en contrôlant la trajectoire.' where canonical_name = 'Développé couché haltères';
update exercise_catalog set instructions_fr = 'Même mouvement que le développé couché, mais sur banc incliné pour cibler le haut des pectoraux. La barre descend vers le haut de la poitrine, pas le cou.' where canonical_name = 'Développé incliné barre';
update exercise_catalog set instructions_fr = 'Sur banc incliné, pousse les haltères à la verticale au-dessus du haut des pectoraux. Contrôle la descente, ne les laisse pas partir vers l''arrière.' where canonical_name = 'Développé incliné haltères';
update exercise_catalog set instructions_fr = 'Sur banc décliné, jambes bien calées. La barre descend vers le bas de la poitrine. Fais-toi aider pour décrocher la barre du rack en toute sécurité.' where canonical_name = 'Développé décliné barre';
update exercise_catalog set instructions_fr = 'Bras légèrement fléchis en permanence, ouvre les bras sur les côtés en grand arc jusqu''à sentir l''étirement pectoral, puis remonte en refermant les bras comme pour enlacer un arbre.' where canonical_name = 'Écarté couché haltères';
update exercise_catalog set instructions_fr = 'Poulies hautes, buste légèrement penché en avant. Ramène les poignées devant toi en grand arc, coudes légèrement fléchis, sans bouger le torse.' where canonical_name = 'Écarté à la poulie vis-à-vis';
update exercise_catalog set instructions_fr = 'Mains à largeur d''épaules, corps gainé et aligné des talons à la tête. Descends jusqu''à presque toucher le sol puis pousse, sans casser les hanches.' where canonical_name = 'Pompes';
update exercise_catalog set instructions_fr = 'Bras tendus au départ, buste droit. Descends jusqu''à un angle de 90° au coude en gardant les coudes près du corps pour cibler les triceps, puis remonte.' where canonical_name = 'Dips';
update exercise_catalog set instructions_fr = 'Assis, dos bien calé, bras parallèles au sol. Rapproche les poignées lentement en contractant les pectoraux au centre, puis reviens en étirant sans à-coup.' where canonical_name = 'Pec deck / butterfly';
update exercise_catalog set instructions_fr = 'Prise pronation (paumes vers l''avant), écartée selon la largeur souhaitée. Tire jusqu''à ce que la barre touche le haut de la poitrine en ramenant les épaules vers le bas et l''arrière, sans balancer le buste.' where canonical_name = 'Tractions pronation';
update exercise_catalog set instructions_fr = 'Prise supination (paumes vers toi), mains rapprochées. Tire jusqu''à ce que la tête dépasse la barre en gardant les coudes près du corps ; sollicite bien les biceps.' where canonical_name = 'Tractions supination';
update exercise_catalog set instructions_fr = 'Buste légèrement incliné en arrière, poitrine sortie. Amène la barre vers le haut de la poitrine en ramenant les coudes vers le bas et l''arrière, sans tirer avec les avant-bras.' where canonical_name = 'Tirage vertical poulie';
update exercise_catalog set instructions_fr = 'Genoux légèrement fléchis, buste penché presque parallèle au sol, dos plat. Tire la barre vers le bas du buste en gardant les coudes près du corps, sans à-coup du dos.' where canonical_name = 'Rowing barre';
update exercise_catalog set instructions_fr = 'Un genoux et une main en appui sur le banc, dos plat et parallèle au sol. Tire l''haltère vers la hanche en gardant le coude près du corps, sans faire pivoter le buste.' where canonical_name = 'Rowing haltère unilatéral';
update exercise_catalog set instructions_fr = 'Assis, genoux légèrement fléchis, dos droit. Tire la poignée vers l''abdomen en gardant le buste stable et les coudes près du corps, sans t''aider du balancier du dos.' where canonical_name = 'Rowing poulie basse';
update exercise_catalog set instructions_fr = 'Dos plat en permanence, la barre longe les tibias. Pousse avec les jambes en redressant le buste, épaules en arrière en position debout ; ne jamais arrondir le bas du dos.' where canonical_name = 'Soulevé de terre';
update exercise_catalog set instructions_fr = 'Genoux légèrement fléchis et fixes, recule les hanches en gardant le dos plat jusqu''à sentir l''étirement des ischios, barre proche des jambes, puis reviens en poussant les hanches vers l''avant.' where canonical_name = 'Soulevé de terre roumain';
update exercise_catalog set instructions_fr = 'Poulie haute, corde ou double poignée. Tire vers le visage en écartant les mains, coudes hauts et parallèles au sol ; excellent pour les épaules et la posture.' where canonical_name = 'Face pull';
update exercise_catalog set instructions_fr = 'Bras tendus le long du corps, haltères en main. Élève les épaules le plus haut possible sans plier les coudes ni aider avec les biceps, tiens une seconde en haut.' where canonical_name = 'Shrugs haltères';
update exercise_catalog set instructions_fr = 'À plat ventre, bras tendus devant toi. Lève simultanément bras, jambes et poitrine, tiens 2 secondes en contractant le bas du dos, puis redescends lentement.' where canonical_name = 'Superman / extension lombaire';
update exercise_catalog set instructions_fr = 'Barre au niveau des clavicules, prise plus large que les épaules. Pousse la barre à la verticale au-dessus de la tête en gardant le buste gainé, sans cambrer excessivement.' where canonical_name = 'Développé militaire barre';
update exercise_catalog set instructions_fr = 'Assis, dos soutenu, haltères à hauteur d''épaules paumes vers l''avant. Pousse à la verticale jusqu''à ce qu''elles se touchent presque en haut, puis redescends lentement.' where canonical_name = 'Développé militaire haltères';
update exercise_catalog set instructions_fr = 'Buste droit et immobile, lève les haltères sur les côtés jusqu''à hauteur d''épaules, coudes légèrement fléchis, comme si tu versais de l''eau vers l''avant en haut du mouvement.' where canonical_name = 'Élévations latérales haltères';
update exercise_catalog set instructions_fr = 'Buste immobile, lève un haltère devant toi jusqu''à légèrement au-dessus de l''horizontale, paume vers le bas, puis alterne avec l''autre bras sans balancer.' where canonical_name = 'Élévations frontales haltères';
update exercise_catalog set instructions_fr = 'Bras tendus croisés devant toi au départ, ouvre-les vers l''arrière et l''extérieur en gardant les bras droits, sans les plier davantage en cours de mouvement.' where canonical_name = 'Oiseau / élévations arrière';
update exercise_catalog set instructions_fr = 'Haltères devant les épaules, paumes vers toi. Pousse en haut tout en pivotant les poignets pour finir paumes vers l''avant, puis inverse la rotation en redescendant.' where canonical_name = 'Développé Arnold';
update exercise_catalog set instructions_fr = 'Coudes fixes près du torse, prise à largeur d''épaules. Monte la barre en ne bougeant que les avant-bras, contracte fort en haut, puis redescends lentement.' where canonical_name = 'Curl biceps barre';
update exercise_catalog set instructions_fr = 'Même principe que le curl barre droite, mais la prise angulée de la barre EZ soulage les poignets. Coudes immobiles, contraction franche en haut.' where canonical_name = 'Curl biceps barre EZ';
update exercise_catalog set instructions_fr = 'Coudes près du corps, paumes vers l''avant. Monte en ne bougeant que les avant-bras, contracte le biceps en haut, redescends lentement en contrôlant.' where canonical_name = 'Curl biceps haltères';
update exercise_catalog set instructions_fr = 'Paumes face à toi (prise neutre) du début à la fin du mouvement, coudes fixes. Monte et descends en alternant les bras sans les faire pivoter.' where canonical_name = 'Curl marteau haltères';
update exercise_catalog set instructions_fr = 'Bras plaqués contre le pupitre, prise à largeur d''épaules. Descends jusqu''à extension complète du bras, puis remonte sans décoller les triceps du pupitre.' where canonical_name = 'Curl pupitre';
update exercise_catalog set instructions_fr = 'Coudes fixes près du corps, prise supination sur la barre de poulie basse. Monte en ne bougeant que les avant-bras, contracte en haut, redescends lentement.' where canonical_name = 'Curl à la poulie';
update exercise_catalog set instructions_fr = 'Coudes fixes le long du corps, avant-bras vers le haut au départ. Pousse la barre vers le bas jusqu''à extension complète des bras, sans bouger les coudes vers l''avant.' where canonical_name = 'Extension triceps poulie';
update exercise_catalog set instructions_fr = 'Allongé sur banc, bras verticaux et fixes. Descends la barre vers le front en pliant seulement les coudes, puis remonte en tendant les bras.' where canonical_name = 'Extension triceps barre EZ';
update exercise_catalog set instructions_fr = 'Haltère tenu à deux mains au-dessus de la tête, coudes fixes et rapprochés. Descends derrière la tête jusqu''à sentir l''étirement du triceps, puis remonte.' where canonical_name = 'Extension triceps haltère nuque';
update exercise_catalog set instructions_fr = 'Identique à l''extension triceps barre EZ : allongé, bras verticaux et fixes, la barre descend vers le front puis remonte par extension du coude.' where canonical_name = 'Barre au front';
update exercise_catalog set instructions_fr = 'Barre posée sur le haut du dos, pieds à largeur d''épaules. Descends en poussant les hanches vers l''arrière, genoux dans l''axe des pieds sans dépasser les orteils, jusqu''à cuisses parallèles au sol ou plus bas.' where canonical_name = 'Squat arrière barre';
update exercise_catalog set instructions_fr = 'Barre posée sur les déltoïdes avant, coudes hauts. Même descente que le squat arrière, mais le buste reste plus droit ; pousse par le milieu du pied en remontant.' where canonical_name = 'Squat avant barre';
update exercise_catalog set instructions_fr = 'Pieds à largeur d''épaules sur la plateforme, dos bien calé. Descends jusqu''à un angle de 90° au genoux sans verrouiller les genoux en haut, pousse par les talons.' where canonical_name = 'Presse à cuisses';
update exercise_catalog set instructions_fr = 'Grand pas en avant, descends jusqu''à ce que le genoux arrière frôle le sol, tibia avant vertical sans dépasser les orteils, puis pousse pour avancer d''un pas.' where canonical_name = 'Fentes marchées';
update exercise_catalog set instructions_fr = 'Descends en fente, puis pousse explosivement pour sauter et changer de jambe en l''air, réception souple directement en fente opposée.' where canonical_name = 'Fentes sautées';
update exercise_catalog set instructions_fr = 'Descends en squat, puis pousse explosivement par l''avant du pied pour sauter le plus haut possible, réception souple en repliant directement dans le squat suivant.' where canonical_name = 'Squats sautés';
update exercise_catalog set instructions_fr = 'Tibia calé contre le rouleau, genoux aligné sur l''axe de la machine. Tends la jambe complètement en pausant en haut, puis redescends sans relâcher la tension.' where canonical_name = 'Leg extension';
update exercise_catalog set instructions_fr = 'Pied arrière surélevé derrière toi, haltères en main. Descends en gardant le genoux avant aligné sur le pied, puis pousse par le talon avant pour remonter.' where canonical_name = 'Fentes bulgares';
update exercise_catalog set instructions_fr = 'Chevilles posées sur le ballon, hanches décollées du sol. Ramène le ballon vers les fessiers en fléchissant les genoux, contracte les ischios, puis reviens lentement.' where canonical_name = 'Leg curl allongé';
update exercise_catalog set instructions_fr = 'Dos calé, tibias sous le rouleau rembourré. Fléchis les genoux pour ramener le rouleau vers l''arrière des cuisses, tiens la contraction, puis reviens lentement.' where canonical_name = 'Leg curl assis';
update exercise_catalog set instructions_fr = 'Barre sur le haut du dos comme au squat, genoux légèrement fléchis et fixes. Pench e le buste vers l''avant en poussant les hanches en arrière, dos plat, jusqu''à quasi-parallèle au sol, puis reviens en poussant les hanches.' where canonical_name = 'Good morning barre';
update exercise_catalog set instructions_fr = 'Haut du dos calé contre un banc, barre roulée au-dessus du bassin. Pousse par les talons pour lever les hanches à la verticale, contracte les fessiers en haut, puis redescends.' where canonical_name = 'Hip thrust barre';
update exercise_catalog set instructions_fr = 'Allongé au sol, barre au-dessus du bassin, pieds à plat. Pousse par les talons pour lever les hanches, le poids reposant sur le haut du dos et les talons, puis redescends.' where canonical_name = 'Pont fessier';
update exercise_catalog set instructions_fr = 'Barre sur le haut du dos, pieds à largeur d''épaules. Monte le plus haut possible sur la pointe des pieds en contractant les mollets, tiens une seconde, puis redescends en étirant complètement.' where canonical_name = 'Mollets debout';
update exercise_catalog set instructions_fr = 'Avant-pieds sur la plateforme de la presse, jambes presque tendues. Pousse par l''avant du pied pour monter le plus haut possible, puis redescends en étirant complètement le mollet.' where canonical_name = 'Mollets à la presse';
update exercise_catalog set instructions_fr = 'Genoux sous le coussin rembourré, avant-pieds sur la plateforme. Descends les talons pour étirer le mollet, puis monte le plus haut possible en contractant, tiens une seconde.' where canonical_name = 'Mollets assis';
update exercise_catalog set instructions_fr = 'Appui sur les avant-bras et les pointes de pieds, coudes sous les épaules. Corps parfaitement aligné de la tête aux talons, sans creuser ni arrondir le bas du dos.' where canonical_name = 'Gainage planche';
update exercise_catalog set instructions_fr = 'Genoux fléchis, mains légèrement de chaque côté de la tête sans tirer sur la nuque. Décolle seulement les épaules du sol de quelques centimètres en contractant les abdominaux, redescends lentement.' where canonical_name = 'Crunch';
update exercise_catalog set instructions_fr = 'Suspendu à la barre, bras tendus. Relève les jambes jusqu''à ce que le buste et les jambes forment un angle de 90°, sans te balancer, puis redescends lentement.' where canonical_name = 'Relevé de jambes suspendu';
update exercise_catalog set instructions_fr = 'Assis, buste incliné en V avec les cuisses, pieds calés ou surélevés. Fais pivoter le buste d''un côté à l''autre en gardant les bras tendus devant toi.' where canonical_name = 'Russian twist';
update exercise_catalog set instructions_fr = 'Position de pompe, ramène un genoux vers la poitrine puis inverse rapidement les jambes en alternance, bassin stable et gainé tout du long.' where canonical_name = 'Mountain climbers';
update exercise_catalog set instructions_fr = 'Poignets qui font tourner la corde, petits sauts légers sur l''avant du pied. Garde un rythme régulier plutôt que de sauter haut.' where canonical_name = 'Corde à sauter';
update exercise_catalog set instructions_fr = 'Hanches qui initient le mouvement (pas les bras) : recule les fessiers, puis pousse les hanches vers l''avant pour projeter le kettlebell à hauteur d''épaules, bras relâchés.' where canonical_name = 'Kettlebell swing';
update exercise_catalog set instructions_fr = 'Descends en squat complet avec les haltères aux épaules, puis enchaîne sans pause en poussant explosivement les haltères à la verticale au-dessus de la tête en te relevant.' where canonical_name = 'Thruster haltères';

-- ============================================================
-- FIN DE LA MIGRATION
-- ============================================================